export const metadata = {
  title: "Privacy Policy | Dr. Diego F. Cuadros",
}

export default function PrivacyPage() {
  return (
    <div className="container py-12 px-4 md:px-6 max-w-3xl">
      <h1 className="text-4xl font-bold mb-4 font-sans">Privacy Policy</h1>
      <p className="text-sm font-serif text-muted-foreground mb-8">Last updated: June 2026</p>
      <div className="space-y-6 font-serif text-slate-700 dark:text-slate-300 leading-relaxed">
        <p>
          This site may use basic analytics and standard browser logs to improve functionality and monitor site stability.
          We do not sell personal data.
        </p>
        <section>
          <h2 className="text-2xl font-semibold mb-2">Information We Collect</h2>
          <ul className="list-disc list-inside space-y-1">
            <li>Publicly provided contact messages submitted through institutional channels.</li>
            <li>Device and usage metadata automatically generated by your browser.</li>
            <li>Optional analytics data if hosted by our platform provider.</li>
          </ul>
        </section>
        <section>
          <h2 className="text-2xl font-semibold mb-2">How We Use Information</h2>
          <ul className="list-disc list-inside space-y-1">
            <li>Maintain and improve performance and reliability.</li>
            <li>Protect against fraud, abuse, and security risks.</li>
            <li>Evaluate aggregate traffic patterns for design improvements.</li>
          </ul>
        </section>
        <section>
          <h2 className="text-2xl font-semibold mb-2">Data Retention</h2>
          <p>
            We retain only what is necessary to support routine operations and site maintenance. You may request deletion of
            personal correspondence data through the Contact page.
          </p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold mb-2">External Services</h2>
          <p>
            External links to social platforms and publication profiles may set their own cookies and collect usage data
            under their terms.
          </p>
        </section>
      </div>
    </div>
  )
}
