// Publications data for Dr. Diego F. Cuadros organized by research categories
export const allPublications = [
  // 1. HIV Hotspots
  {
    title: "Mapping HIV clustering: a strategy for identifying populations at high risk of HIV infection in sub-Saharan Africa",
    authors: "Cuadros D.F., Awad S.F., Abu-Raddad L.J.",
    journal: "International Journal of Health Geographics",
    year: 2013,
    links: [{ label: "Read", href: "https://www.researchgate.net/profile/Diego-Cuadros/research" }],
    tags: ["HIV Hotspots"],
    imageUrl: "/Images/Publications/publication-1.png",
    summary: "This foundational study establishes spatial clustering techniques to identify geographic areas with concentrated HIV transmission in sub-Saharan Africa. Using geospatial methods, the research maps HIV hotspots and demonstrates how geographic targeting can optimize resource allocation and intervention strategies. The approach provides a strategic framework for identifying populations at highest risk, enabling more efficient deployment of prevention and treatment programs. This methodology has become essential for public health planning, allowing targeted interventions in areas with greatest need and supporting evidence-based policy decisions for HIV prevention and control efforts across the region.",
  },
  {
    title: "Spatial variability in HIV prevalence declines in several countries in sub-Saharan Africa",
    authors: "Cuadros D.F., Abu-Raddad L.J.",
    journal: "Health & Place",
    year: 2014,
    links: [{ label: "Read", href: "https://www.researchgate.net/profile/Diego-Cuadros/research" }],
    tags: ["HIV Hotspots"],
    imageUrl: "/Images/Publications/publication-2.png",
    summary: "This comprehensive analysis documents uneven HIV prevalence declines across sub-Saharan African countries from 2003-2013, revealing significant spatial heterogeneity in epidemic control. Some communities experienced dramatic reductions exceeding 50%, while others remained static or showed minimal improvement. The study demonstrates that national average declines can obscure critical localized stagnation, highlighting areas where interventions have been less effective. These findings underscore the importance of spatially disaggregated monitoring and targeted interventions rather than uniform national strategies. The research advocates for localized approaches that address specific community needs and emphasizes the necessity of geographic precision in HIV surveillance and response planning.",
  },
  {
    title: "Geographical patterns of HIV sero-discordancy in high HIV prevalence countries in sub-Saharan Africa",
    authors: "Cuadros D.F., Abu-Raddad L.J.",
    journal: "International Journal of Environmental Research and Public Health",
    year: 2016,
    links: [{ label: "Read", href: "https://www.researchgate.net/profile/Diego-Cuadros/research" }],
    tags: ["HIV Hotspots"],
    imageUrl: "/Images/Publications/publication-3.png",
    summary: "Analyzing demographic and health survey data from seven high-prevalence countries, this study maps spatial patterns of HIV sero-discordant couples across sub-Saharan Africa. The research found that sero-discordant couple clusters overlapped with high-prevalence areas in Kenya, Malawi, and Tanzania, with no distinct discordancy hotspots independent of overall prevalence. With epidemic decline, projections suggest sero-discordant couple fractions will rise to 70-92% by 2030. These findings highlight the growing importance of couple-based testing and prevention strategies, emphasizing the need for targeted interventions that address both partners' needs and support prevention within relationships.",
  },
  {
    title: "Towards UNAIDS Fast-Track goals: Targeting priority geographic areas for HIV prevention and care in Zimbabwe",
    authors: "Cuadros D.F., et al.",
    journal: "AIDS",
    year: 2019,
    links: [{ label: "Read", href: "https://www.researchgate.net/profile/Diego-Cuadros/research" }],
    tags: ["HIV Hotspots"],
    imageUrl: "/Images/Publications/publication-4.png",
    summary: "Using ZDHS (2015) and ZIMPHIA (2016) data, this study generated high-resolution maps of HIV prevalence, ART coverage, and viral suppression across Zimbabwe. The research identified geographic areas—particularly in urban centers like Harare, Bulawayo, and Matabeleland regions—where high-density HIV populations lacked adequate services. Despite overall progress toward 90-90-90 targets, many hotspots remained under-resourced. The study recommends locally tailored intervention strategies, increased service coverage in identified hotspots, and integration of geospatial analysis into resource allocation processes. This approach enables efficient targeting to close gaps in HIV diagnosis, treatment, and viral suppression at the community level.",
  },
  {
    title: "Beyond HIV prevalence: identifying people living with HIV within underserved areas in South Africa",
    authors: "Kim H., Tanser F., Tomita A., Vandormael A., Cuadros D.F.",
    journal: "BMJ Global Health",
    year: 2021,
    links: [{ label: "Read", href: "https://www.researchgate.net/profile/Diego-Cuadros/research" }],
    tags: ["HIV Hotspots"],
    imageUrl: "/Images/Publications/publication-5.png",
    summary: "This innovative study applies spatial accessibility models and health-facility catchment analyses to identify communities where people living with HIV face the greatest travel burdens to access care. By overlaying residence data with road-network travel times to clinics, the research defines \"underserved\" areas as those beyond 30- or 60-minute travel thresholds. Findings highlighted rural districts in KwaZulu-Natal and Eastern Cape as critical service gaps. The study advocates for decentralized ART delivery and mobile services to bridge spatial barriers, demonstrating how geographic analysis can inform service delivery strategies to improve HIV care accessibility and reduce treatment disparities.",
  },
  {
    title: "Role of high-risk communities in HIV spread in rural South Africa",
    authors: "Cuadros D.F., de Oliveira T., Gräf T., et al.",
    journal: "PLOS Global Public Health",
    year: 2022,
    links: [{ label: "Read", href: "https://www.researchgate.net/profile/Diego-Cuadros/research" }],
    tags: ["HIV Hotspots"],
    imageUrl: "/Images/Publications/publication-6.png",
    summary: "Using transmission network analysis, this study identifies communities acting as reservoir hubs in rural KwaZulu-Natal HIV transmission. Researchers found that individuals in these high-risk geographic hubs had elevated onward transmission potential, even while receiving treatment. These communities served as epidemiological bridges connecting to wider regions, perpetuating viral spread across geographic boundaries. The molecular epidemiology approach reveals how specific locations drive ongoing transmission despite treatment scale-up. The study recommends prioritizing hub locations for intensified testing, PrEP delivery, and enhanced community engagement strategies to disrupt established transmission pathways and reduce epidemic persistence in rural settings.",
  },

  // HIV Care Access
  {
    title: "Geospatial Patterns of Progress towards UNAIDS \"95-95-95\" Targets and Community Vulnerability in Zambia",
    authors: "Cuadros D.F., Chowdhury M.D.T., Milali M., et al.",
    journal: "BMJ Global Health",
    year: 2023,
    links: [{ label: "Read", href: "https://www.researchgate.net/profile/Diego-Cuadros/research" }],
    tags: ["HIV Care Access"],
    imageUrl: "/Images/Publications/publication-7.png",
    summary: "Analyzing 2016 ZAMPHIA data using Gaussian kernel interpolation, hotspot mapping, and geospatial k-means clustering, this study mapped progress and gaps in each \"95\" target (diagnosis, treatment, viral suppression) across Zambia. Each cascade indicator displayed unique spatial patterns, resulting in four distinct regional clusters with varying performance levels. Key factors linked to gaps included younger age, male sex, and low wealth status. Performance did not correlate with HIV prevalence, highlighting the need for targeted approaches. The study calls for region-specific interventions—tailoring testing access, treatment availability, and community engagement strategies—to efficiently close gaps in the HIV care continuum.",
  },
  {
    title: "Progress Towards UNAIDS 95-95-95 Targets in Zimbabwe: Sociodemographic Constraints and Geospatial Heterogeneity",
    authors: "Chowdhury M.D.T., Bershteyn A., Milali M., Citron D.T., Nyimbili S., Musuka G., Cuadros D.F.",
    journal: "Communications Medicine",
    year: 2025,
    links: [{ label: "Read", href: "https://www.researchgate.net/profile/Diego-Cuadros/research" }],
    tags: ["HIV Care Access"],
    imageUrl: "/Images/Publications/publication-8.png",
    summary: "This comprehensive analysis of 2020 Zimbabwe Population-based HIV Impact Assessment data evaluates progress on UNAIDS 95-95-95 goals using geospatial methods including kernel interpolation, hotspot analysis, and k-means clustering. The research uncovered four distinct regional clusters with differing performance gaps across diagnosis, treatment, and viral suppression. Key risk factors for falling short of targets included being young, male, employed, or of minority/no religion. Border and underserved areas—particularly Mashonaland West and Midlands—showed slower progress. The study recommends tailored local interventions, emphasizing enhanced testing and treatment access in lagging districts to achieve equitable progress toward epidemic control.",
  },
  {
    title: "Moving Beyond HIV Prevalence Hotspots: Shifting the Focus Towards Geospatial Hotspots of UNAIDS 95-95-95 Targets in Sub-Saharan Africa",
    authors: "Cuadros D.F., et al.",
    journal: "BMJ Global Health",
    year: 2024,
    links: [{ label: "Read", href: "https://www.researchgate.net/profile/Diego-Cuadros/research" }],
    tags: ["HIV Care Access"],
    imageUrl: "/Images/Publications/publication-9.png",
    summary: "This paradigm-shifting study examines spatial distributions of HIV prevalence versus geospatial coverage of UNAIDS 95-95-95 cascade targets across sub-Saharan Africa. The research argues that traditional prevalence-based hotspot mapping overlooks critical gaps in care—regions may have low prevalence but poor viral suppression or treatment reach. Drawing on examples from Zambia and Zimbabwe, the study highlights regional disparities in treatment and viral load metrics. The authors propose shifting geospatial targeting to address care cascade gaps rather than focusing solely on prevalence. They advocate using viral-load and ART coverage maps to guide interventions aimed at closing diagnosis, treatment, and suppression gaps.",
  },
  {
    title: "When distance matters: Mapping HIV healthcare–underserved communities in Sub-Saharan Africa",
    authors: "Kim H., Musuka G., Mukandavire Z., Cuadros D.F.",
    journal: "PLOS Global Public Health",
    year: 2021,
    links: [{ label: "Read", href: "https://www.researchgate.net/profile/Diego-Cuadros/research" }],
    tags: ["HIV Care Access"],
    imageUrl: "/Images/Publications/publication-10.png",
    summary: "This groundbreaking study generated high-resolution maps identifying areas in sub-Saharan Africa where travel time to healthcare exceeds 10, 30, or 60 minutes, overlaying these with people living with HIV density estimates. The research identified over 7 million people living with HIV residing more than 10 minutes away on foot, and approximately 1.5 million more than 60 minutes away. Underserved zones were predominant in central and southern Africa. The study highlights critical spatial barriers to care access, advocating for decentralized services, mobile clinics, and geographically targeted interventions to reduce delays in ART access and ultimately prevent new HIV infections through improved treatment coverage.",
  },
] 